name: koopdv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - scipy
  - pytorch
  - torchvision
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - jupyter
  - jupyterlab
  - ipython
  - dpk-forecast
